/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Projekt_edit;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.RandomAccessFile;

/**
 *
 * @author JakubKrolik
 */
public class Program extends java.applet.Applet {

    /**
     * Initializes the applet Program
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenu1 = new javax.swing.JMenu();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        setName(""); // NOI18N
        setLayout(null);

        jTextField2.setToolTipText("");
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField2.setName(""); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(60, 10, 110, 20);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(170, 10, 110, 20);

        jButton1.setText("Zapisz");
        jButton1.setPreferredSize(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(30, 30, 140, 23);

        jButton2.setText("Wyświetl");
        jButton2.setPreferredSize(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(170, 30, 130, 23);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 310, 50);

        jLabel1.setText("Rodzaj");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 60, 14);

        jLabel2.setText("Imie");
        add(jLabel2);
        jLabel2.setBounds(280, 10, 40, 14);
        add(jSeparator1);
        jSeparator1.setBounds(240, 220, 0, 2);

        jLabel3.setText("Usuń");
        add(jLabel3);
        jLabel3.setBounds(20, 150, 50, 14);
        add(jTextField1);
        jTextField1.setBounds(60, 120, 110, 20);

        jButton3.setText("Szukaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(170, 120, 90, 23);

        jTextField4.setEditable(false);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4);
        jTextField4.setBounds(260, 120, 60, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add(jTextField5);
        jTextField5.setBounds(60, 150, 110, 20);

        jButton4.setText("Usuń");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(170, 150, 150, 23);

        jLabel4.setText("Szukaj");
        add(jLabel4);
        jLabel4.setBounds(20, 120, 50, 14);

        jButton5.setText("Usuń wszystko");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(60, 170, 260, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String rodzaj=""; //= jTextField2.getText();
        String imie=""; //= jTextField3.getText();

        boolean dlugosc = ((jTextField2.getText().length()>=1)&&(jTextField3.getText().length()>=1)); //boolean spacja = ((jTextField2.getText().equals(" "))||(jTextField3.getText().equals(" ")));

        boolean r_space=true;
        boolean i_space=true;
        
        if(dlugosc){
            rodzaj = jTextField2.getText();
            imie = jTextField3.getText();
            
            for(int i=0; i<rodzaj.length(); i++){
                if(rodzaj.charAt(i)==' '){
                    r_space=false;
                }
            }
            for(int i=0; i<imie.length(); i++){
                if(imie.charAt(i)==' '){
                    i_space=false;
                }
            }
            
            rodzaj = rodzaj.toUpperCase();

            
            
            if(r_space && i_space){
            
                Zwierzeta z = new Zwierzeta(rodzaj, imie);
                z.zapisz();

                jTextField2.setText("");
                jTextField3.setText("");
                jTextArea1.setText(" Wpisano do bazy");
            }
        }
        else{
            jTextArea1.setText(" Pola muszą być wypełnione");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Zwierzeta z = new Zwierzeta("", "");
        z.odczyt();
        //jTextField2.setText(z.rodzaj);
        //jTextField3.setText(z.imie);
        jTextArea1.setText(z.odczyt());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Zwierzeta z = new Zwierzeta("", "");
        z.odczyt();
        jTextArea1.setText(z.odczyt());
        
        
        String stare = jTextArea1.getText();
        String szukaj = jTextField1.getText();
        
        int q = stare.indexOf(szukaj); 
        if(q==-1){jTextField4.setText("Nie"); jTextArea1.setBackground(Color.red);}
        else{jTextField4.setText("Tak"); jTextArea1.setBackground(Color.green);}

        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Zwierzeta z = new Zwierzeta("", "");
        String x = jTextField5.getText();
        boolean first_condition = x.length()>=3;
        boolean second_condition = true;
        boolean third_condition = true;
        String literka = x.substring(1,2);
        char znak;
        for(int i=0; i<x.length(); i++){
            if(x.charAt(i)==' '){
                if(x.charAt(i+1)==' '){
                    second_condition = false;
                }
            }
        }
        if(!(literka.toUpperCase().equals(literka))) third_condition = false;      
        if(first_condition && second_condition && third_condition) z.usun(x);
        else jTextArea1.setText(" Wpisz \"NAZWA nazwa\"");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Zwierzeta z = new Zwierzeta("", "");
        z.delete();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
