/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lis15.powtorki;

/**
 *
 * @author JakubKrolik
 */
public class Drugi extends java.applet.Applet {

    /**
     * Initializes the applet Drugi
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(null);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(100, 110, 73, 23);

        jTextField1.setText("jTextField1");
        add(jTextField1);
        jTextField1.setBounds(60, 70, 59, 20);

        jTextField2.setText("jTextField2");
        add(jTextField2);
        jTextField2.setBounds(150, 70, 59, 20);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(90, 150, 106, 66);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String wartosc1="";
        String wartosc2="";
        String wynik_p="";
        Double kon_1;
        Double kon_2;
        Double wynik;
        
        wartosc1=jTextField1.getText();
        wartosc2=jTextField2.getText();
        
        
        try{
            kon_1=Double.parseDouble(wartosc1);
            kon_2=Double.parseDouble(wartosc2);
            
            wynik=kon_1+kon_2;
            
            wynik_p=wynik.toString();
            
            jTextArea1.setText(wynik_p);
            
        }
        catch(Exception e){
            jTextArea1.setText("Blad");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
