package paź18;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class Szosty extends java.applet.Applet {

    /**
     * Initializes the applet Szosty
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        button1 = new java.awt.Button();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        textField6 = new java.awt.TextField();
        textField8 = new java.awt.TextField();
        textField7 = new java.awt.TextField();
        textField9 = new java.awt.TextField();
        textField10 = new java.awt.TextField();
        textField11 = new java.awt.TextField();
        textField12 = new java.awt.TextField();
        textField13 = new java.awt.TextField();
        textField14 = new java.awt.TextField();

        setLayout(null);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        add(textField1);
        textField1.setBounds(60, 20, 40, 20);

        textField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField2ActionPerformed(evt);
            }
        });
        add(textField2);
        textField2.setBounds(130, 20, 40, 20);
        add(textField3);
        textField3.setBounds(200, 20, 40, 20);

        button1.setLabel("Oblicz");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(40, 40, 200, 20);

        textField4.setEnabled(false);
        textField4.setMinimumSize(new java.awt.Dimension(16, 20));
        textField4.setText("C");
        textField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField4ActionPerformed(evt);
            }
        });
        add(textField4);
        textField4.setBounds(180, 20, 17, 20);

        textField5.setEnabled(false);
        textField5.setText("A");
        textField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField5ActionPerformed(evt);
            }
        });
        add(textField5);
        textField5.setBounds(40, 20, 15, 20);

        textField6.setEnabled(false);
        textField6.setText("Pierwiastek drugi");
        textField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField6ActionPerformed(evt);
            }
        });
        add(textField6);
        textField6.setBounds(40, 150, 130, 20);

        textField8.setEnabled(false);
        textField8.setText("B");
        textField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField8ActionPerformed(evt);
            }
        });
        add(textField8);
        textField8.setBounds(110, 20, 16, 20);

        textField7.setEnabled(false);
        textField7.setText("Delta");
        textField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField7ActionPerformed(evt);
            }
        });
        add(textField7);
        textField7.setBounds(40, 70, 40, 20);

        textField9.setEnabled(false);
        add(textField9);
        textField9.setBounds(90, 70, 150, 20);

        textField10.setEnabled(false);
        textField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField10ActionPerformed(evt);
            }
        });
        add(textField10);
        textField10.setBounds(170, 90, 70, 20);

        textField11.setEnabled(false);
        textField11.setText("Liczba pierwiastkow");
        textField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField11ActionPerformed(evt);
            }
        });
        add(textField11);
        textField11.setBounds(40, 90, 120, 20);

        textField12.setEnabled(false);
        textField12.setText("Pierwiastek pierwszy");
        textField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField12ActionPerformed(evt);
            }
        });
        add(textField12);
        textField12.setBounds(40, 110, 130, 20);

        textField13.setEnabled(false);
        textField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField13ActionPerformed(evt);
            }
        });
        add(textField13);
        textField13.setBounds(40, 130, 200, 20);

        textField14.setEnabled(false);
        textField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField14ActionPerformed(evt);
            }
        });
        add(textField14);
        textField14.setBounds(40, 170, 200, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void textField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField2ActionPerformed

    private void textField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField4ActionPerformed

    private void textField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField5ActionPerformed

    private void textField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField6ActionPerformed

    private void textField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField8ActionPerformed

    private void textField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField7ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String aa, bb, cc;
        Double a, b, c;

        aa = textField1.getText();
        bb = textField2.getText();
        cc = textField3.getText();

        try {
            a = Double.parseDouble(aa);
            b = Double.parseDouble(bb);
            c = Double.parseDouble(cc);

            Double delta;

            delta = ((b * b) - (4 * a * c));

            String delta_string;
            String pierwszy_string;
            String drugi_string;
            String jeden_string;
            Double pierwszy = (-(b) - Math.sqrt(delta)) / 2 * a;
            Double drugi = (-(b) + Math.sqrt(delta)) / 2 * a;
            Double jeden = (-(b)) / 2 * a;

            if (a == 0) {
                if(b == 0){
                    if(c == 0){
                        textField9.setText("Brak");
                        textField10.setText("Nieskonczenie wiele");
                        textField13.setText("");
                        textField14.setText("");
                    }
                    else {
                        textField9.setText("Brak");
                        textField10.setText("0");
                        textField13.setText("Brak");
                        textField14.setText("Brak");
                    }
                }
                else {
                    textField9.setText("Brak");
                    textField10.setText("1");
                    textField13.setText("0");
                    textField14.setText("Brak");      
                }
            }
            else
            {
                    if (delta > 0) {
                        textField10.setText("2");
                        delta_string = Double.toString(delta);
                        textField9.setText(delta_string);
                        pierwszy_string = Double.toString(pierwszy);
                        drugi_string = Double.toString(drugi);
                        textField13.setText(pierwszy_string);
                        textField14.setText(drugi_string);
                    }
                    if (delta == 0) {
                        textField10.setText("1");
                        delta_string = Double.toString(delta);
                        textField9.setText(delta_string);
                        jeden_string = Double.toString(jeden);
                        textField13.setText(jeden_string);
                        textField14.setText(jeden_string);
                    }
                    if (delta < 0) {
                        textField10.setText("0");
                        delta_string = Double.toString(delta);
                        textField9.setText(delta_string);
                        textField13.setText("Brak");
                        textField14.setText("Brak");
                    }
            }
        } catch (Exception e) {
            textField9.setText("Błąd");
            textField10.setText("Błąd");
            textField13.setText("Błąd");
            textField14.setText("Błąd");
        }


    }//GEN-LAST:event_button1ActionPerformed

    private void textField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField11ActionPerformed

    private void textField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField12ActionPerformed

    private void textField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField14ActionPerformed

    private void textField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField10ActionPerformed

    private void textField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField13ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField10;
    private java.awt.TextField textField11;
    private java.awt.TextField textField12;
    private java.awt.TextField textField13;
    private java.awt.TextField textField14;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField6;
    private java.awt.TextField textField7;
    private java.awt.TextField textField8;
    private java.awt.TextField textField9;
    // End of variables declaration//GEN-END:variables
}
