/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
package lis29;
public class MójProgram extends java.applet.Applet {
     
    /**
     * Initializes the applet MójProgram
     */
    public void init() {
        try {
         
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        textField3 = new java.awt.TextField();
        button3 = new java.awt.Button();

        setLayout(null);
        add(textField1);
        textField1.setBounds(110, 50, 100, 40);
        add(textField2);
        textField2.setBounds(230, 50, 120, 40);

        button1.setLabel("Zapis");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(20, 180, 60, 30);

        button2.setLabel("odczyt");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(100, 180, 70, 30);
        add(textField3);
        textField3.setBounds(20, 50, 60, 40);

        button3.setLabel("Następny");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(260, 180, 70, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        String imie = textField1.getText();
        String nazwisko = textField2.getText();
        int lp = Integer.parseInt(textField3.getText().trim());
       
        Osoba o = new Osoba(lp, imie, nazwisko);
        o.zapisz();
        
        textField1.setText(" ");
        textField2.setText(" ");
        textField3.setText(" ");
    }//GEN-LAST:event_button1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        Osoba o = new Osoba(0,"", "");
         o.odczyt();
        textField1.setText(o.imie);
        textField2.setText(o.nazwisko);
    }//GEN-LAST:event_button2ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
           Osoba o = new Osoba(0,"", "");
           int wsk = Integer.parseInt(textField3.getText());
           wsk++;
           o.odczyt2(wsk);
           
    }//GEN-LAST:event_button3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables
}
